import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/main.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "VikingGym",
  description: "Generated by create next app",
  icons: "/gymlogo.png"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
